user_token: NmE0YzRjMzEtNTM2Zi00NDY5LThmNzItZTE1YmE2MTZkNGE4XzMw

session:
  key: t8BAvb1SagRDW86gv7TR4GVYvFIcbctqMkbsFmlDoLM=
admin:
  email: admin@admin.com
  password: admin
mongo:
  host: localhost
  port: 27017
  db: BlackjackBotDatabase
  user: BlackjackBot
  password: BlackjackBotPwd
  uuidRepresentation: standard
  collections:
    players: players
    admins: admins
    game_settings: game_settings
redis:
  host: localhost
  port: 6379
  user: bjbot
  password: bjbot
  db: 0
rabbit:
  host: localhost
  port: 5672
  user: guest
  password: guest
  queue_name: vk_polling
bot:
  token: 71537a16b313e2356b4fc47241558c813f25c22468524fad590a288c24713410349ea3603e95395a13a5c
  group_id: 202369435
game:
  min_bet: 1
  max_bet: 10000
  start_cash: 1000
  bonus: 1000
  bonus_period: 5  # minutes
  num_of_decks: 1



