version: "3"

services:
  rabbit:
    image: ivaaahn/bjbot-rabbit:latest
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_data_volume:/var/lib/rabbit/
      - rabbit_logs_volume:/var/log/rabbit/
    restart: unless-stopped

  redis:
    image: ivaaahn/bjbot-redis:1.0
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    volumes:
      - redis_data_volume:/data
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PWD
      - MONGO_INITDB_DATABASE=$MONGO_INIT_DB
    volumes:
      - mongo_data_volume:/data/db
    restart: unless-stopped

  api:
    image: ivaaahn/bjbot-api:1.1
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    restart: unless-stopped

  poller:
    image: ivaaahn/bjbot-poller:1.1
    container_name: poller
    depends_on:
      - rabbit
    restart: unless-stopped

  worker:
    image: ivaaahn/bjbot-worker:1.1
    container_name: worker
    depends_on:
      - redis
      - mongo
      - rabbit
    restart: unless-stopped


volumes:
  redis_data_volume:
  mongo_data_volume:
  rabbit_data_volume:
  rabbit_logs_volume:
